In [1]:
import numpy as np

a=np.array([1,2,3,4,5,6])
print(type(a))
print(a.shape)
print(a.dtype)
print(a)

<class 'numpy.ndarray'>
(6,)
int64
[1 2 3 4 5 6]


In [2]:
a=np.array(a,dtype='float32')
print(a.dtype)

float32


In [3]:
print(a)

[1. 2. 3. 4. 5. 6.]


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,1])
print("2d Matrix:",b)

(2, 3)
1 2 5
2d Matrix: [[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
c=np.ones((3,4))
print(c.shape)
print('c:',c)
d=np.zeros((2,2))
print('d:',d)

(3, 4)
c: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d: [[0. 0.]
 [0. 0.]]


In [6]:
e=np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
f=np.random.random((2,2))
print(f)

[[0.29836588 0.00413576]
 [0.17797024 0.28186622]]


In [8]:
g=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
h=g[:1,1:3]
print(h)

[[2 3]]


In [10]:
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)
print('using bool index:',a[bool_idx])
print('direct:',a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
using bool index: [3 4 5 6]
direct: [3 4 5 6]


In [11]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [12]:
x2=np.sqrt(x)
print(x2)

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [13]:
x3=np.arange(12)
print(x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
z=x3.reshape(2,6)
print(z)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [15]:
z.itemsize

8

In [16]:
help(np.ndarray.itemsize)

Help on getset descriptor numpy.ndarray.itemsize:

itemsize
    Length of one array element in bytes.
    
    Examples
    --------
    >>> x = np.array([1,2,3], dtype=np.float64)
    >>> x.itemsize
    8
    >>> x = np.array([1,2,3], dtype=np.complex128)
    >>> x.itemsize
    16



In [17]:
x @ y

array([[19., 22.],
       [43., 50.]])

In [18]:
x.dot(y)

array([[19., 22.],
       [43., 50.]])

In [19]:
re=np.random.default_rng(2)
print(re)

Generator(PCG64)


In [20]:
a=np.ones((2,3),dtype=int)
b=re.random((2,3))
b

array([[0.26161213, 0.29849114, 0.81422574],
       [0.09191594, 0.60010053, 0.72856053]])

In [21]:
c=np.arange(24).reshape(3,2,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [22]:
import sys
np.set_printoptions(threshold=sys.maxsize)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
from math import pi
a0=np.ones(3,dtype=np.int32)
b0=np.linspace(0,pi,3)
c0=a0+b0
c0

array([1.        , 2.57079633, 4.14159265])

In [24]:
d0=np.exp(c0*1j)
d0

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [25]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
s=np.arange(12).reshape(3,4)
print(s)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
a=np.arange(11)**3
a

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [28]:
a[:6:2]=1000
a[: :-1]

array([1000,  729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [29]:
for i in a:
  print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998
9.999999999999998


In [30]:
help(np.fromfunction)

Help on function fromfunction in module numpy:

fromfunction(function, shape, **kwargs)
    Construct an array by executing a function over each coordinate.
    
    The resulting array therefore has a value ``fn(x, y, z)`` at
    coordinate ``(x, y, z)``.
    
    Parameters
    ----------
    function : callable
        The function is called with N parameters, where N is the rank of
        `shape`.  Each parameter represents the coordinates of the array
        varying along a specific axis.  For example, if `shape`
        were ``(2, 2)``, then the parameters would be
        ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
    shape : (N,) tuple of ints
        Shape of the output array, which also determines the shape of
        the coordinate arrays passed to `function`.
    dtype : data-type, optional
        Data-type of the coordinate arrays passed to `function`.
        By default, `dtype` is float.
    
    Returns
    -------
    fromfunction : any
        The 

In [0]:
def f(x,y):
  return 10*x+y

b=np.fromfunction(f,(5,4),dtype=int)

In [32]:
for row in b:
  print(row)


[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [33]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [34]:
help(np.floor)

Help on ufunc object:

floor = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array

In [35]:
a=np.floor(10*re.random((3,4)))
print(a)

[[1. 0. 2. 6.]
 [5. 1. 4. 6.]
 [4. 6. 9. 6.]]


In [36]:
a.ravel()

array([1., 0., 2., 6., 5., 1., 4., 6., 4., 6., 9., 6.])

In [37]:
a.T

array([[1., 5., 4.],
       [0., 1., 6.],
       [2., 4., 9.],
       [6., 6., 6.]])

In [38]:
a.reshape((3,4))

array([[1., 0., 2., 6.],
       [5., 1., 4., 6.],
       [4., 6., 9., 6.]])

In [44]:
a.resize((6,2))
a.shape

(6, 2)

In [0]:
x=np.floor(10*re.random((2,2)))
y=np.floor(10*re.random((2,2)))

In [48]:
np.vstack((x,y))

array([[3., 1.],
       [3., 5.],
       [8., 7.],
       [3., 9.]])

In [49]:
np.hstack((x,y))

array([[3., 1., 8., 7.],
       [3., 5., 3., 9.]])